### PR TITLE
Create Digital_clock.py

### PR DESCRIPTION
**Pull request by djharshit**

### CODE REVIEW

**Review by InvisiblePro — APPROVED** [review]
Good Work!

**Comment by InvisiblePro** [comment]
Hey! @djharshit, Kindly inform that whether this repo is excluded or not?

**Comment by djharshit** [comment]
First of all, thank you for accepting the PR. The repo is not yet excluded, and my PR is in 7 day review period.

**Comment by InvisiblePro** [comment]
Okay, thanks to you too!!
Keep going in Event!
All the best ✨ 
[Check out this project too](https://github.com/InvisiblePro/CV_Projects)

**Pull request merged**
